export const PRODUCTION_STORAGE_BUCKET = "tennis-images";
export const DEMO_STORAGE_BUCKET = "tennis-images-demo";

export const SUPABASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET || PRODUCTION_STORAGE_BUCKET;

export const IS_PORTFOLIO_DEMO_CLIENT = SUPABASE_STORAGE_BUCKET === DEMO_STORAGE_BUCKET;
