import type { ObjectId } from "mongodb";
import type { ProgramApprovalStatus, ProgramPublicationStatus } from "./program.types";
export const PROGRAM_COLLECTION_NAME = "program_posts";
export type MongoProgramAttachment = {
  bucket: string;
  objectPath: string;
  originalFileName: string;
  label: string;
  contentType: "application/pdf";
  byteSize: number;
  storedAt: Date;
};
export type MongoProgramDocument = {
  _id: ObjectId;
  slug: string;
  category: string;
  title: string;
  summary: string;
  purpose: string;
  body: string[];
  operationStatusLabel: string | null;
  sortOrder: number;
  publicationStatus: ProgramPublicationStatus;
  approvalStatus: ProgramApprovalStatus;
  publishedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  deletedAt?: Date | null;
  coverGalleryItemId?: ObjectId | null;
  attachment?: MongoProgramAttachment | null;
};
