import { ObjectId, type ClientSession, type Db } from "mongodb";
import type { AdminPrincipal } from "../admin-auth/admin-auth.types";
import { programAuditActions, programAuditChangedFields, type ProgramAuditAction, type ProgramAuditActor, type ProgramAuditChangedField, type ProgramAuditSnapshot } from "./program.audit";
import { isProgramApprovalStatus, isProgramPublicationStatus, isValidProgramSlug } from "./program.types";
export const PROGRAM_AUDIT_COLLECTION_NAME = "program_audit_events";
export type MongoProgramAuditEventDocument = { _id: ObjectId; schemaVersion: 1; programId: ObjectId; action: ProgramAuditAction; actor: ProgramAuditActor; occurredAt: Date; fromVersionAt: Date | null; toVersionAt: Date; before: ProgramAuditSnapshot | null; after: ProgramAuditSnapshot; changedFields: ProgramAuditChangedField[] };
const validDate = (v: unknown): v is Date => v instanceof Date && !Number.isNaN(v.getTime());
function validSnapshot(v: ProgramAuditSnapshot): boolean { return isValidProgramSlug(v.slug) && v.category.trim().length > 0 && v.title.trim().length > 0 && v.summary.trim().length > 0 && v.purpose.trim().length > 0 && Array.isArray(v.body) && v.body.length > 0 && (v.operationStatusLabel === null || v.operationStatusLabel.trim().length > 0) && Number.isInteger(v.sortOrder) && isProgramPublicationStatus(v.publicationStatus) && isProgramApprovalStatus(v.approvalStatus) && (v.publishedAt === null || validDate(v.publishedAt)); }
function actor(value: AdminPrincipal): ProgramAuditActor { if (!ObjectId.isValid(value.id) || new ObjectId(value.id).toHexString() !== value.id.toLowerCase() || !value.displayName.trim() || value.role !== "admin") throw new Error("감사 이벤트 관리자 정보가 유효하지 않습니다."); return { adminId: new ObjectId(value.id), displayName: value.displayName, role: value.role }; }
export async function insertProgramAuditEvent(input: { database: Db; session: ClientSession; eventId: ObjectId; programId: ObjectId; action: ProgramAuditAction; actor: AdminPrincipal; occurredAt: Date; fromVersionAt: Date | null; toVersionAt: Date; before: ProgramAuditSnapshot | null; after: ProgramAuditSnapshot; changedFields: readonly ProgramAuditChangedField[] }): Promise<void> { const changedFields = Array.from(input.changedFields); if (!programAuditActions.includes(input.action) || !validDate(input.occurredAt) || (input.fromVersionAt !== null && !validDate(input.fromVersionAt)) || !validDate(input.toVersionAt) || (input.before !== null && !validSnapshot(input.before)) || !validSnapshot(input.after) || changedFields.some(f => !programAuditChangedFields.includes(f)) || new Set(changedFields).size !== changedFields.length) throw new Error("감사 이벤트 데이터가 유효하지 않습니다."); await input.database.collection<MongoProgramAuditEventDocument>(PROGRAM_AUDIT_COLLECTION_NAME).insertOne({ _id: input.eventId, schemaVersion: 1, programId: input.programId, action: input.action, actor: actor(input.actor), occurredAt: input.occurredAt, fromVersionAt: input.fromVersionAt, toVersionAt: input.toVersionAt, before: input.before, after: input.after, changedFields }, { session: input.session }); }
