import { ObjectId } from "mongodb";
import { type AdminUserDocument } from "@/features/admin-auth/admin-auth.repository";
import { adminUserStatuses,isAdminRole,type AdminRole,type AdminUserStatus } from "@/features/admin-auth/admin-auth.types";
import { normalizeAdminEmail } from "@/features/admin-auth/admin-auth.service";
import { isValidAdminPasswordHash } from "@/features/admin-auth/password";
const object=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).length===keys.length&&keys.every(k=>k in v);
const date=(v:unknown):v is Date=>v instanceof Date&&!Number.isNaN(v.getTime());
const controls=/[\u0000-\u001f\u007f]/; const html=/<\/?[A-Za-z][^>]*>/;
export const validEmail=(v:unknown):v is string=>typeof v==="string"&&v===v.trim()&&v.length>=3&&v.length<=254&&!controls.test(v)&&!/[\s]/.test(v)&&v.indexOf("@")>0&&v.indexOf("@")<v.length-1;
export const validName=(v:unknown):v is string=>typeof v==="string"&&v===v.trim()&&v.length>=2&&v.length<=50&&!controls.test(v)&&!html.test(v);
export function isValidStoredAdminUser(value:unknown):value is AdminUserDocument{if(!object(value)||!(value._id instanceof ObjectId)||!validEmail(value.email)||value.normalizedEmail!==value.email.toLowerCase()||!validName(value.displayName)||!isValidAdminPasswordHash(value.passwordHash)||!isAdminRole(value.role)||!adminUserStatuses.includes(value.status as AdminUserStatus)||!date(value.createdAt)||!date(value.updatedAt)||value.updatedAt<value.createdAt)return false;return value.lastLoginAt===null||(date(value.lastLoginAt)&&value.lastLoginAt>=value.createdAt&&value.lastLoginAt<=value.updatedAt)}
export type CreateValue={email:string;displayName:string;role:AdminRole;password:string};
export function validateCreateAdminUser(v:unknown):{ok:true;value:CreateValue}|{ok:false;fieldErrors:Record<string,string>}{const e:Record<string,string>={};if(!object(v)||!exact(v,["user","createConfirmed"])||v.createConfirmed!==true||!object(v.user)||!exact(v.user,["email","displayName","role","password","passwordConfirmation"]))return{ok:false,fieldErrors:{form:"입력 형식이 올바르지 않습니다."}};const email=typeof v.user.email==="string"?v.user.email.trim():"";if(!validEmail(email))e.email="올바른 이메일을 입력해 주세요.";if(!validName(typeof v.user.displayName==="string"?v.user.displayName.trim():null))e.displayName="표시 이름은 2~50자의 한 줄 평문이어야 합니다.";if(!isAdminRole(v.user.role))e.role="역할을 선택해 주세요.";if(typeof v.user.password!=="string"||v.user.password.length<12||v.user.password.length>128)e.password="비밀번호는 12~128자여야 합니다.";if(v.user.password!==v.user.passwordConfirmation)e.passwordConfirmation="비밀번호가 일치하지 않습니다.";if(Object.keys(e).length)return{ok:false,fieldErrors:e};return{ok:true,value:{email:normalizeAdminEmail(email)===email.toLowerCase()?email:email,displayName:(v.user.displayName as string).trim(),role:v.user.role as AdminRole,password:v.user.password as string}}}
const iso=(v:unknown):v is string=>typeof v==="string"&&!Number.isNaN(new Date(v).getTime())&&new Date(v).toISOString()===v;
export function validateUpdateAdminUser(v:unknown){if(!object(v)||!exact(v,["expectedUpdatedAt","user","updateConfirmed"])||!iso(v.expectedUpdatedAt)||v.updateConfirmed!==true||!object(v.user)||!exact(v.user,["displayName","role","status"])||!validName(typeof v.user.displayName==="string"?v.user.displayName.trim():null)||!isAdminRole(v.user.role)||!adminUserStatuses.includes(v.user.status as AdminUserStatus))return{ok:false as const,fieldErrors:{form:"입력 형식이 올바르지 않습니다."}};return{ok:true as const,value:{expectedUpdatedAt:new Date(v.expectedUpdatedAt),displayName:(v.user.displayName as string).trim(),role:v.user.role as AdminRole,status:v.user.status as AdminUserStatus}}}
export function validateRevokeAdminUserSessions(v:unknown){if(!object(v)||!exact(v,["expectedUpdatedAt","revokeConfirmed"])||!iso(v.expectedUpdatedAt)||v.revokeConfirmed!==true)return{ok:false as const,fieldErrors:{form:"입력 형식이 올바르지 않습니다."}};return{ok:true as const,value:{expectedUpdatedAt:new Date(v.expectedUpdatedAt)}}}
