"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { authenticatedSWRFetcher } from "@/lib/fetchers/authenticatedSWRFetcher";
import { AlertCircle, CheckCircle2, Clock, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import useSWR from "swr";

type CareItem = { id: string; nickname: string; racket: { brand: string; model: string }; playFrequency: string; lastStringingAt: string; lastStringProductId: string | null; stringSnapshot: any; reminderEnabled: boolean; recentStringProductAvailable: boolean | null; careStatus: { nextRecommendedAt: string; daysRemaining: number; progressPercent: number; state: "good" | "prepare" | "due" } };
const freqLabels: Record<string, string> = { monthly: "월 1~2회", weekly: "주 1회", biweekly_plus: "주 2~3회", heavy: "주 4회 이상" };
const stateMeta = { good: { label: "양호", icon: CheckCircle2 }, prepare: { label: "교체 준비", icon: Clock }, due: { label: "교체 권장", icon: AlertCircle } } as const;
const today = new Date().toISOString().slice(0, 10);
const emptyForm = { nickname: "", brand: "", model: "", playFrequency: "weekly", lastStringingAt: today, reminderEnabled: false, stringName: "", gauge: "", tensionMain: "", tensionCross: "", latestCompletedApplicationId: "" };

function dateLabel(value: string) { return new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "short", day: "numeric" }).format(new Date(value)); }

export default function RacketCareClient() {
  const { data, error, isLoading, mutate } = useSWR<{ items: CareItem[]; suggestedImport: any }>("/api/users/me/racket-care", authenticatedSWRFetcher);
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<CareItem | null>(null); const [form, setForm] = useState(emptyForm); const [errors, setErrors] = useState<Record<string,string>>({}); const [saving, setSaving] = useState(false); const [deletingId, setDeletingId] = useState<string | null>(null);
  const items = data?.items ?? [];
  const startCreate = (suggested?: any) => { setEditing(null); setErrors({}); setForm(suggested ? { ...emptyForm, nickname: suggested.nickname ?? "", brand: suggested.racket?.brand ?? "", model: suggested.racket?.model ?? "", playFrequency: suggested.playFrequency ?? "weekly", lastStringingAt: String(suggested.lastStringingAt ?? today).slice(0,10), stringName: suggested.stringSnapshot?.name ?? "", gauge: suggested.stringSnapshot?.gauge ?? "", tensionMain: suggested.stringSnapshot?.tensionMain ?? "", tensionCross: suggested.stringSnapshot?.tensionCross ?? "", latestCompletedApplicationId: suggested.latestCompletedApplication?.id ?? "" } : emptyForm); setOpen(true); };
  const startEdit = (item: CareItem) => { setEditing(item); setErrors({}); setForm({ nickname: item.nickname, brand: item.racket.brand, model: item.racket.model, playFrequency: item.playFrequency, lastStringingAt: item.lastStringingAt.slice(0,10), reminderEnabled: item.reminderEnabled, stringName: item.stringSnapshot?.name ?? "", gauge: item.stringSnapshot?.gauge ?? "", tensionMain: item.stringSnapshot?.tensionMain ?? "", tensionCross: item.stringSnapshot?.tensionCross ?? "", latestCompletedApplicationId: "" }); setOpen(true); };
  const payload = useMemo(() => ({ nickname: form.nickname, racket: { brand: form.brand, model: form.model }, playFrequency: form.playFrequency, lastStringingAt: form.lastStringingAt, reminderEnabled: form.reminderEnabled, stringSnapshot: { name: form.stringName, gauge: form.gauge, tensionMain: form.tensionMain, tensionCross: form.tensionCross }, latestCompletedApplicationId: form.latestCompletedApplicationId }), [form]);
  async function save() { if (saving) return; setSaving(true); setErrors({}); const res = await fetch(editing ? `/api/users/me/racket-care/${editing.id}` : "/api/users/me/racket-care", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const json = await res.json().catch(()=>({})); setSaving(false); if (!res.ok) { setErrors(json.errors ?? { form: json.message ?? "저장하지 못했습니다." }); return; } setOpen(false); await mutate(); }
  async function remove(id: string) { setSaving(true); const res = await fetch(`/api/users/me/racket-care/${id}`, { method: "DELETE" }); setSaving(false); setDeletingId(null); if (res.ok) await mutate(); }
  async function toggleReminder(item: CareItem, checked: boolean) { await fetch(`/api/users/me/racket-care/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reminderEnabled: checked }) }); await mutate(); }
  return <div className="space-y-6">
    <div className="rounded-2xl border border-border bg-card p-5 shadow-sm bp-sm:p-6"><p className="text-ui-label font-semibold uppercase tracking-[0.14em] text-primary">라켓 케어 패스</p><h1 className="mt-2 text-ui-section-title font-semibold text-foreground">내 라켓 케어</h1><p className="mt-2 break-keep text-ui-body-sm text-muted-foreground">마지막 교체일과 플레이 빈도를 기준으로 다음 스트링 교체 시점을 확인해보세요.</p><p className="mt-1 break-keep text-ui-body-sm text-muted-foreground">플레이 빈도와 마지막 교체일을 기준으로 계산한 예상 시점</p></div>
    {isLoading && <Card><CardContent className="p-5 text-muted-foreground">라켓 케어 정보를 불러오는 중...</CardContent></Card>}
    {error && <Card><CardContent className="p-5 text-destructive">라켓 케어 정보를 불러오지 못했습니다.</CardContent></Card>}
    {!isLoading && !error && items.length === 0 && <Card><CardContent className="space-y-4 p-5"><p className="font-semibold">등록된 라켓이 없습니다.</p><p className="break-keep text-ui-body-sm text-muted-foreground">테니스 프로필 또는 완료된 교체 이력이 있으면 기존 정보에서 가져올 수 있어요.</p><Button className="min-h-10 w-full bp-sm:w-auto" onClick={() => startCreate(data?.suggestedImport)}><Plus className="mr-2 h-4 w-4" />{data?.suggestedImport ? "기존 정보에서 가져오기" : "첫 라켓 등록하기"}</Button></CardContent></Card>}
    <div className="grid gap-4 bp-lg:grid-cols-2">{items.map((item) => { const meta = stateMeta[item.careStatus.state]; const Icon = meta.icon; return <Card key={item.id} className="min-w-0 rounded-2xl"><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle className="break-words text-ui-card-title-lg">{item.nickname}</CardTitle><Badge variant={item.careStatus.state === "due" ? "destructive" : item.careStatus.state === "prepare" ? "brand" : "secondary"} className="shrink-0"><Icon className="mr-1 h-3.5 w-3.5" />{meta.label}</Badge></div><p className="break-words text-ui-body-sm text-muted-foreground">{item.racket.brand} {item.racket.model}</p></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 text-ui-body-sm"><p>마지막 교체일: <span className="font-medium">{dateLabel(item.lastStringingAt)}</span></p><p>예상 다음 교체일: <span className="font-medium">{dateLabel(item.careStatus.nextRecommendedAt)}</span></p><p>플레이 빈도: <span className="font-medium">{freqLabels[item.playFrequency] ?? item.playFrequency}</span></p>{item.stringSnapshot?.name && <p className="break-words">최근 스트링: <span className="font-medium">{item.stringSnapshot.name}</span>{item.stringSnapshot.gauge ? ` / ${item.stringSnapshot.gauge}` : ""}{item.stringSnapshot.tensionMain || item.stringSnapshot.tensionCross ? ` / ${item.stringSnapshot.tensionMain ?? "-"}-${item.stringSnapshot.tensionCross ?? "-"}LB` : ""}</p>}</div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${item.careStatus.progressPercent}%` }} /></div><div className="flex flex-col gap-2 bp-sm:flex-row bp-sm:flex-wrap"><Button asChild className="min-h-10 w-full bp-sm:w-auto"><Link href={`/products/recommend?from=racket-care&freq=${item.playFrequency}&careItemId=${item.id}`}>맞춤 스트링 추천받기</Link></Button>{item.lastStringProductId && item.recentStringProductAvailable ? <Button asChild variant="outline" className="min-h-10 w-full bp-sm:w-auto"><Link href={`/products/${item.lastStringProductId}?from=apply&careItemId=${item.id}`}>최근 스트링 다시 보기</Link></Button> : item.lastStringProductId ? <p className="text-ui-body-sm text-muted-foreground">현재 판매 중인 스트링에서 다시 추천받아 주세요.</p> : null}<Button variant="outline" className="min-h-10 w-full bp-sm:w-auto" onClick={() => startEdit(item)}>정보 수정</Button><Button variant="outline" className="min-h-10 w-full bp-sm:w-auto" onClick={() => setDeletingId(item.id)}><Trash2 className="mr-2 h-4 w-4" />삭제</Button></div><div className="flex min-h-10 items-center gap-3"><Switch id={`reminder-${item.id}`} checked={item.reminderEnabled} onCheckedChange={(checked) => toggleReminder(item, checked)} /><Label htmlFor={`reminder-${item.id}`}>교체 알림 받기</Label></div></CardContent></Card>; })}</div>
    {items.length > 0 && <Button variant="outline" className="min-h-10 w-full bp-sm:w-auto" onClick={() => startCreate()} disabled={items.length >= 5}>라켓 추가 등록</Button>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "라켓 정보 수정" : "라켓 등록"}</DialogTitle></DialogHeader><div className="grid gap-3"><Field id="nickname" label="라켓 별칭" value={form.nickname} error={errors.nickname} onChange={(v)=>setForm({...form,nickname:v})}/><Field id="brand" label="브랜드" value={form.brand} error={errors.brand} onChange={(v)=>setForm({...form,brand:v})}/><Field id="model" label="모델" value={form.model} error={errors.model} onChange={(v)=>setForm({...form,model:v})}/><div><Label htmlFor="playFrequency">플레이 빈도</Label><select id="playFrequency" className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-ui-body-sm" value={form.playFrequency} onChange={(e)=>setForm({...form,playFrequency:e.target.value})}>{Object.entries(freqLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{errors.playFrequency && <p className="mt-1 text-ui-label text-destructive">{errors.playFrequency}</p>}</div><div><Label htmlFor="lastStringingAt">마지막 교체일</Label><Input id="lastStringingAt" type="date" max={today} value={form.lastStringingAt} onChange={(e)=>setForm({...form,lastStringingAt:e.target.value})}/>{errors.lastStringingAt && <p className="mt-1 text-ui-label text-destructive">{errors.lastStringingAt}</p>}</div><Field id="stringName" label="최근 스트링명(선택)" value={form.stringName} onChange={(v)=>setForm({...form,stringName:v})}/><div className="grid gap-2 bp-sm:grid-cols-3"><Field id="gauge" label="게이지" value={form.gauge} onChange={(v)=>setForm({...form,gauge:v})}/><Field id="tensionMain" label="메인 텐션" value={form.tensionMain} onChange={(v)=>setForm({...form,tensionMain:v})}/><Field id="tensionCross" label="크로스 텐션" value={form.tensionCross} onChange={(v)=>setForm({...form,tensionCross:v})}/></div>{errors.form && <p className="text-ui-body-sm text-destructive">{errors.form}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)} disabled={saving}>취소</Button><Button onClick={save} disabled={saving}>{saving ? "저장 중..." : "저장"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!deletingId} onOpenChange={(v)=>!v&&setDeletingId(null)}><DialogContent><DialogHeader><DialogTitle>라켓 정보를 삭제할까요?</DialogTitle></DialogHeader><p className="text-ui-body-sm text-muted-foreground">삭제해도 주문·교체 신청 이력은 변경되지 않습니다.</p><DialogFooter><Button variant="outline" onClick={()=>setDeletingId(null)} disabled={saving}>취소</Button><Button variant="destructive" onClick={()=>deletingId&&remove(deletingId)} disabled={saving}>삭제</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Field({ id, label, value, error, onChange }: { id: string; label: string; value: string; error?: string; onChange: (v:string)=>void }) { return <div><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={(e)=>onChange(e.target.value)} aria-invalid={!!error}/>{error && <p className="mt-1 text-ui-label text-destructive">{error}</p>}</div>; }
