import { ObjectId } from "mongodb";
import { getMongoClient, getMongoDatabase } from "@/lib/mongodb";
import type { AdminPrincipal } from "@/features/admin-auth/admin-auth.types";
import { insertInquiryAuditEvent, listInquiryAuditEvents } from "./inquiry.audit-repository";
import type { InquiryDocument, InquiryKind, InquiryStatus } from "./inquiry.types";
import { inquiryRetentionDays, inquiryKinds, inquiryStatuses } from "./inquiry.types";
const allowed: Record<InquiryStatus, InquiryStatus[]> = { received: ["in_review", "completed"], in_review: ["contacted", "completed"], contacted: ["in_review", "completed"], completed: ["in_review", "archived"], archived: ["in_review"] };
export function canTransitionInquiryStatus(from: InquiryStatus, to: InquiryStatus) { return from === to || allowed[from].includes(to); }
const visible = (now: Date) => ({ $or: [{ deleteAfter: null }, { deleteAfter: { $gt: now } }] });
const valid = (d: InquiryDocument) => inquiryKinds.includes(d.kind) && inquiryStatuses.includes(d.status) && d.updatedAt instanceof Date;
export async function listAdminInquiries(input: { status?: InquiryStatus; kind?: InquiryKind; page: number; pageSize: 20 }) { const db = await getMongoDatabase(); const filter = { ...visible(new Date()), ...(input.status ? { status: input.status } : {}), ...(input.kind ? { kind: input.kind } : {}) }; const collection = db.collection<InquiryDocument>("inquiries"); const [documents, total] = await Promise.all([collection.find(filter).sort({ createdAt: -1, _id: -1 }).skip((input.page - 1) * input.pageSize).limit(input.pageSize).toArray(), collection.countDocuments(filter)]); return { total, items: documents.filter(valid).map((d) => ({ id: d._id.toHexString(), reference: d.reference, kind: d.kind, status: d.status, name: d.name, contactChannels: d.phone && d.email ? "전화·이메일" : d.phone ? "전화" : "이메일", createdAt: d.createdAt.toISOString(), updatedAt: d.updatedAt.toISOString() })) }; }
export async function getAdminInquiryCounts() { const db = await getMongoDatabase(); const rows = await db.collection<InquiryDocument>("inquiries").aggregate<{ _id: InquiryStatus; count: number }>([{ $match: visible(new Date()) }, { $group: { _id: "$status", count: { $sum: 1 } } }]).toArray(); const result = Object.fromEntries(inquiryStatuses.map((s) => [s, 0])) as Record<InquiryStatus, number>; rows.forEach((r) => result[r._id] = r.count); return { ...result, total: rows.reduce((n, r) => n + r.count, 0) }; }
export async function getAdminInquiry(id: string) { if (!ObjectId.isValid(id)) return null; const db = await getMongoDatabase(); const document = await db.collection<InquiryDocument>("inquiries").findOne({ _id: new ObjectId(id), ...visible(new Date()) }); if (!document || !valid(document)) return null; const audit = await listInquiryAuditEvents(db, document._id); return { ...document, id, _id: undefined, createdAt: document.createdAt.toISOString(), updatedAt: document.updatedAt.toISOString(), privacyConsentedAt: document.privacyConsentedAt.toISOString(), completedAt: document.completedAt?.toISOString() ?? null, archivedAt: document.archivedAt?.toISOString() ?? null, deleteAfter: document.deleteAfter?.toISOString() ?? null, audit: audit.map((e) => ({ action: e.action, displayName: e.actor.displayName, occurredAt: e.occurredAt.toISOString(), fromStatus: e.fromStatus, toStatus: e.toStatus, changedFields: e.changedFields })) }; }
export type UpdateResult = { ok: true } | { ok: false; reason: "not_found" | "invalid_document" | "edit_conflict" | "invalid_transition" };
export async function updateAdminInquiry(input: { id: string; expectedUpdatedAt: Date; status: InquiryStatus; internalNote: string; actor: AdminPrincipal; now?: Date }): Promise<UpdateResult> { const client = await getMongoClient(); const db = await getMongoDatabase(); const session = client.startSession(); try { return await session.withTransaction(async () => { const id = new ObjectId(input.id); const existing = await db.collection<InquiryDocument>("inquiries").findOne({ _id: id, ...visible(input.now ?? new Date()) }, { session }); if (!existing) return { ok: false, reason: "not_found" }; if (!valid(existing)) return { ok: false, reason: "invalid_document" }; if (existing.updatedAt.getTime() !== input.expectedUpdatedAt.getTime()) return { ok: false, reason: "edit_conflict" }; if (!canTransitionInquiryStatus(existing.status, input.status)) return { ok: false, reason: "invalid_transition" }; const at = new Date(Math.max((input.now ?? new Date()).getTime(), input.expectedUpdatedAt.getTime() + 1)); let completedAt = existing.completedAt, archivedAt = existing.archivedAt, deleteAfter = existing.deleteAfter; if (input.status === "completed" && existing.status !== "completed") { completedAt = at; archivedAt = null; deleteAfter = new Date(at.getTime() + inquiryRetentionDays * 86400000); } else if (input.status === "in_review" && (existing.status === "completed" || existing.status === "archived")) { completedAt = null; archivedAt = null; deleteAfter = null; } else if (existing.status === "completed" && input.status === "archived") archivedAt = at; const changedFields = [...(existing.status !== input.status ? ["status" as const] : []), ...(existing.internalNote !== input.internalNote ? ["internalNote" as const] : [])]; const updated = await db.collection<InquiryDocument>("inquiries").updateOne({ _id: id, updatedAt: input.expectedUpdatedAt, ...visible(at) }, { $set: { status: input.status, internalNote: input.internalNote, updatedAt: at, completedAt, archivedAt, deleteAfter } }, { session }); if (!updated.matchedCount) return { ok: false, reason: "edit_conflict" }; await db.collection("inquiry_audit_events").updateMany({ inquiryId: id }, { $set: { deleteAfter } }, { session }); await insertInquiryAuditEvent(db, { _id: new ObjectId(), inquiryId: id, action: "updated", actor: { adminId: new ObjectId(input.actor.id), displayName: input.actor.displayName, role: input.actor.role }, occurredAt: at, fromVersionAt: existing.updatedAt, toVersionAt: at, fromStatus: existing.status, toStatus: input.status, changedFields, deleteAfter }, session); return { ok: true }; }, { readConcern: { level: "snapshot" }, writeConcern: { w: "majority" } }); } finally { await session.endSession(); } }
