import { type Filter } from "mongodb";
import { getMongoDatabase } from "@/lib/mongodb";
import { GALLERY_ITEM_COLLECTION_NAME, type MongoGalleryItemDocument } from "./gallery.mongo-schema";
import { getSeoulCalendarDate, isGalleryConsentReadyForPublication, isValidGallerySlug } from "./gallery.types";
import type { GalleryRepository, PublicGalleryItem, PublicGalleryMedia, PublicGallerySummary } from "./gallery.repository";
function filter(now=new Date()): Filter<MongoGalleryItemDocument> { const today=getSeoulCalendarDate(now); return { publicationStatus:"published", approvalStatus:"approved", publishedAt:{$ne:null,$lte:now}, archivedAt:null, consentWithdrawnAt:null, $and:[{$or:[{deletedAt:{$exists:false}},{deletedAt:null}]},{$or:[{displayStartOn:null},{displayStartOn:{$lte:today}}]},{$or:[{displayEndOn:null},{displayEndOn:{$gte:today}}]},{$or:[{subjectPresence:{$in:["none","non_identifiable"]},consentStatus:"not_required",consentCheckedOn:null,consentReferenceCode:null},{subjectPresence:"identifiable",consentStatus:"confirmed",consentCheckedOn:{$type:"string"},consentReferenceCode:{$type:"string"}}]}] }; }
const projection={slug:1,title:1,category:1,description:1,altText:1,activityDate:1,"media.width":1,"media.height":1,publishedAt:1,subjectPresence:1,consentStatus:1,consentCheckedOn:1,consentReferenceCode:1,consentWithdrawnAt:1} as const;
function value(d:MongoGalleryItemDocument): PublicGalleryItem|null { if(!isValidGallerySlug(d.slug)||!d.title?.trim()||!d.category?.trim()||!d.description?.trim()||!d.altText?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(d.activityDate)||!d.publishedAt||!isGalleryConsentReadyForPublication(d)||!Number.isInteger(d.media?.width)||!Number.isInteger(d.media?.height)) return null; return {slug:d.slug,title:d.title,category:d.category,description:d.description,altText:d.altText,activityDate:d.activityDate,width:d.media.width,height:d.media.height,publishedAt:d.publishedAt.toISOString()}; }
export class MongoGalleryRepository implements GalleryRepository { async listPublished():Promise<readonly PublicGallerySummary[]>{const docs=await(await getMongoDatabase()).collection<MongoGalleryItemDocument>(GALLERY_ITEM_COLLECTION_NAME).find(filter(),{projection}).sort({activityDate:-1,publishedAt:-1,_id:-1}).limit(60).toArray();return docs.flatMap(d=>{const v=value(d);return v?[v]:[]})} async findPublishedBySlug(slug:string){if(!isValidGallerySlug(slug))return null;const d=await(await getMongoDatabase()).collection<MongoGalleryItemDocument>(GALLERY_ITEM_COLLECTION_NAME).findOne({...filter(),slug},{projection});return d?value(d):null} async findMediaBySlug(slug:string):Promise<PublicGalleryMedia|null>{if(!isValidGallerySlug(slug))return null;const d=await(await getMongoDatabase()).collection<MongoGalleryItemDocument>(GALLERY_ITEM_COLLECTION_NAME).findOne({...filter(),slug});return d&&value(d)?{bucket:d.media.bucket,objectPath:d.media.objectPath,mimeType:d.media.mimeType,byteSize:d.media.byteSize}:null} }
