"use client";
import { useState, type FormEvent } from "react";
import type { FacilitySpaceInput } from "@/features/facility-spaces/facility-space.types";
import { validateFacilitySpaceInput, type FacilitySpaceFieldErrors } from "@/features/facility-spaces/facility-space.validation";
export type AdminFacilitySpaceFormProps = { mode: "create" | "edit"; id?: string; expectedUpdatedAt: string | null; initialSpace: FacilitySpaceInput };
export function AdminFacilitySpaceForm({ mode, id, expectedUpdatedAt, initialSpace }: AdminFacilitySpaceFormProps) {
  const [space, setSpace] = useState(initialSpace); const [confirmed, setConfirmed] = useState(false); const [errors, setErrors] = useState<FacilitySpaceFieldErrors>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const set = <K extends keyof FacilitySpaceInput>(key: K, value: FacilitySpaceInput[K]) => setSpace((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const validation = validateFacilitySpaceInput(space); if (!validation.ok || !confirmed) { setErrors({ ...(!validation.ok ? validation.fieldErrors : {}), ...(!confirmed ? { saveConfirmed: "공개 가능한 내용인지 확인해 주세요." } : {}) }); setMessage("입력 내용을 확인해 주세요."); return; } setErrors({}); setBusy(true); try { const response = await fetch(mode === "create" ? "/api/admin/site-content/spaces" : `/api/admin/site-content/spaces/${id}`, { method: mode === "create" ? "POST" : "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedUpdatedAt, saveConfirmed: true, space: validation.value }) }); let body: { error?: string; redirectTo?: string; fieldErrors?: FacilitySpaceFieldErrors }; try { body = await response.json(); } catch { setMessage("생활공간 정보를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요."); return; } if (!response.ok || !body.redirectTo) { if (body.error === "validation") { setErrors(body.fieldErrors ?? {}); setMessage("입력 내용을 확인해 주세요."); return; } setMessage(body.error === "edit_conflict" ? "다른 관리자가 공간 정보를 먼저 수정했습니다. 새로고침 후 다시 확인해 주세요." : body.error === "invalid_transition" ? "보관된 공간은 초안으로 복구한 뒤 공개할 수 있습니다." : "생활공간 정보를 저장하지 못했습니다. 잠시 후 다시 시도해 주세요."); return; } window.location.assign(body.redirectTo); } catch { setMessage("네트워크 연결을 확인한 뒤 다시 시도해 주세요."); } finally { setBusy(false); } }
  const error = (key: keyof FacilitySpaceFieldErrors) => errors[key] ? <p id={`${key}-error`} role="alert" className="mt-1 text-small text-destructive">{errors[key]}</p> : null;
  return <form className="space-y-6 rounded-card border p-5" onSubmit={submit} aria-busy={busy}>
    <div><label className="font-bold" htmlFor="title">공간명</label><input id="title" className="mt-2 min-h-11 w-full rounded-control border px-3" value={space.title} onChange={(e) => set("title", e.target.value)} aria-invalid={errors.title ? true : undefined} aria-describedby={errors.title ? "title-error" : undefined}/>{error("title")}</div>
    <div><label className="font-bold" htmlFor="description">공간 설명</label><p id="description-help" className="mt-1 text-small text-muted-foreground">입소자 개인정보와 시설 보안에 영향을 줄 수 있는 상세 위치·출입 정보는 입력하지 마세요.</p><textarea id="description" rows={8} className="mt-2 w-full rounded-control border p-3" value={space.description} onChange={(e) => set("description", e.target.value)} aria-invalid={errors.description ? true : undefined} aria-describedby={`description-help${errors.description ? " description-error" : ""}`}/>{error("description")}</div>
    <div><label className="font-bold" htmlFor="publicationStatus">공개 상태</label><select id="publicationStatus" className="mt-2 min-h-11 w-full border px-3" value={space.publicationStatus} onChange={(e) => set("publicationStatus", e.target.value as FacilitySpaceInput["publicationStatus"])} aria-invalid={errors.publicationStatus ? true : undefined} aria-describedby={errors.publicationStatus ? "publicationStatus-error" : undefined}><option value="draft">초안</option><option value="published">공개</option><option value="archived">보관</option></select>{error("publicationStatus")}</div>
    <div><label className="font-bold" htmlFor="displayOrder">표시 순서</label><input id="displayOrder" type="number" min={1} max={999} className="mt-2 min-h-11 w-full border px-3" value={space.displayOrder} onChange={(e) => set("displayOrder", Number(e.target.value))} aria-invalid={errors.displayOrder ? true : undefined} aria-describedby={errors.displayOrder ? "displayOrder-error" : undefined}/>{error("displayOrder")}</div>
    <label className="flex gap-3"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} aria-invalid={errors.saveConfirmed ? true : undefined} aria-describedby={errors.saveConfirmed ? "saveConfirmed-error" : undefined}/><span>입력한 공간 설명이 개인정보와 시설 보안상 공개 가능한 내용임을 확인했습니다.{error("saveConfirmed")}</span></label>
    {message ? <p role="alert" className="font-bold text-destructive">{message}</p> : null}<button type="submit" disabled={busy || !confirmed} className="min-h-11 rounded-control bg-primary px-5 font-bold text-primary-foreground">{busy ? "저장 중…" : "저장"}</button>
  </form>;
}
