import { Top } from "@toss/tds-mobile";
import { prepareRacketRentalPayment, type AppsPaymentApiError } from "../api/payments";
import { validateApplicant, validateShipping } from "../lib/stringing-application-validation";
import type { RacketRentalDraft } from "../types/racket-rental";
import AppsPaymentCheckoutPanel from "./AppsPaymentCheckoutPanel";
import { validateRefundAccount } from "./RacketRentalStepSix";

export default function RacketRentalStepSeven({ draft, paymentAttemptId, onPaymentAttemptIdChange, onInvalidStep, onPaymentError, onBack, onViewActivity }: { draft: RacketRentalDraft; paymentAttemptId: string | null; onPaymentAttemptIdChange: (v: string | null) => void; onInvalidStep: (step: 1 | 2 | 3 | 4 | 5 | 6, message: string) => void; onPaymentError: (error: AppsPaymentApiError) => void; onBack: () => void; onViewActivity: () => void }) {
  const validate = () => { if (!draft.days) { onInvalidStep(1, "대여 기간을 다시 선택해주세요."); return false; } if (draft.stringingRequested && (!draft.stringProductId || !draft.selectedColor || !draft.selectedGauge)) { onInvalidStep(2, "스트링과 옵션을 다시 선택해주세요."); return false; } if (Object.keys(validateApplicant(draft.applicant)).length) { onInvalidStep(3, "신청자 정보를 다시 확인해주세요."); return false; } if (Object.keys(validateShipping(draft.collectionMethod, draft.shipping)).length) { onInvalidStep(4, "수령 방법과 배송지를 다시 확인해주세요."); return false; } if (draft.stringingRequested && (!draft.work.tensionMain || !draft.work.tensionCross || (draft.collectionMethod === "visit" && (!draft.work.preferredDate || !draft.work.preferredTime)))) { onInvalidStep(5, "작업정보와 방문예약을 다시 확인해주세요."); return false; } if (Object.keys(validateRefundAccount(draft.refundAccount)).length) { onInvalidStep(6, "환급계좌를 다시 확인해주세요."); return false; } return true; };
  return <main className="min-h-dvh bg-white pb-8"><section className="pt-[calc(16px+env(safe-area-inset-top))]"><Top title={<Top.TitleParagraph size={22}>라켓 대여</Top.TitleParagraph>} subtitleBottom={<Top.SubtitleParagraph size={17}>7 / 7 · Toss 로그인·결제</Top.SubtitleParagraph>} /></section><div className="px-6"><AppsPaymentCheckoutPanel paymentPurpose="racket_rental" paymentAttemptId={paymentAttemptId} onPaymentAttemptIdChange={onPaymentAttemptIdChange} validateBeforePrepare={validate} preparePayment={(attemptId, sessionToken) => prepareRacketRentalPayment({ sessionToken, attemptId, racketId: draft.racketId, days: draft.days!, applicant: draft.applicant, collectionMethod: draft.collectionMethod, shipping: draft.shipping, refundAccount: draft.refundAccount, stringing: draft.stringingRequested ? { requested: true, stringProductId: draft.stringProductId, selectedColor: draft.selectedColor, selectedGauge: draft.selectedGauge, work: draft.work } : { requested: false } })} onPaymentError={onPaymentError} onBack={onBack} onViewActivity={onViewActivity} /></div></main>;
}
