import { Top } from "@toss/tds-mobile";
import { useState } from "react";
import { REFUND_BANKS, refundBankLabel } from "../lib/refund-banks";
import { validateRefundAccount } from "../lib/racket-rental-validation";
import { formatGaugeLabel, formatPrice, getStringColorLabel } from "../lib/product-labels";
import { racketBrandLabel } from "../lib/racket-labels";
import type { RacketRentalDraft, RefundAccountDraft } from "../types/racket-rental";

function mask(account: string) { return account.length <= 7 ? "*".repeat(account.length) : `${account.slice(0, 3)}${"*".repeat(account.length - 7)}${account.slice(-4)}`; }

export default function RacketRentalStepSix({ draft, errorMessage = "", onChange, onEdit, onBack, onContinue }: { draft: RacketRentalDraft; errorMessage?: string; onChange: (value: RefundAccountDraft) => void; onEdit: (step: 1 | 2 | 3 | 4 | 5) => void; onBack: () => void; onContinue: () => void }) {
  const [showErrors, setShowErrors] = useState(false); const errors = validateRefundAccount(draft.refundAccount); const fee = draft.days ? Number(draft.racket?.rental?.fee?.[`d${draft.days}` as "d7" | "d15" | "d30"] ?? 0) : 0;
  const row = (title: string, value: string, step: 1 | 2 | 3 | 4 | 5) => <div className="rounded-2xl border border-[#e5e8eb] p-4"><div className="flex justify-between"><b>{title}</b><button type="button" className="border-0 bg-transparent text-[#688d00]" onClick={() => onEdit(step)}>수정</button></div><p className="mb-0 whitespace-pre-line text-sm text-[#4e5968]">{value}</p></div>;
  const submit = () => { setShowErrors(true); if (!Object.keys(errors).length) onContinue(); };
  return <main className="min-h-dvh bg-white px-6 pb-8 text-[#191f28]"><section className="pt-[calc(16px+env(safe-area-inset-top))]"><Top title={<Top.TitleParagraph size={22}>라켓 대여</Top.TitleParagraph>} subtitleBottom={<Top.SubtitleParagraph size={17}>6 / 7 · 환급계좌·최종 확인</Top.SubtitleParagraph>} /></section>
    <h1>보증금 환급 계좌</h1>{errorMessage && <p role="alert" className="text-[#d92d20]">{errorMessage}</p>}<div className="grid gap-3"><select aria-label="환급 은행" value={draft.refundAccount.bank} onChange={(e) => onChange({ ...draft.refundAccount, bank: e.target.value })} className="min-h-12 rounded-xl border px-3"><option value="">은행 선택</option>{REFUND_BANKS.map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select>{showErrors && errors.bank && <small className="text-[#d92d20]">{errors.bank}</small>}<input aria-label="환급 계좌번호" inputMode="numeric" autoComplete="off" maxLength={20} placeholder="계좌번호 숫자 8~20자" value={draft.refundAccount.account} onChange={(e) => onChange({ ...draft.refundAccount, account: e.target.value.replace(/\D/g, "").slice(0, 20) })} className="min-h-12 rounded-xl border px-3" />{showErrors && errors.account && <small className="text-[#d92d20]">{errors.account}</small>}<input aria-label="예금주" autoComplete="off" maxLength={30} placeholder="예금주명" value={draft.refundAccount.holder} onChange={(e) => onChange({ ...draft.refundAccount, holder: e.target.value })} className="min-h-12 rounded-xl border px-3" />{showErrors && errors.holder && <small className="text-[#d92d20]">{errors.holder}</small>}</div>
    <h2 className="mt-8">최종 확인</h2><div className="grid gap-2">{row("라켓·기간", `${racketBrandLabel(draft.racket?.brand)} ${draft.racket?.model ?? ""}\n${draft.days}일 · 대여료 ${formatPrice(fee)} · 보증금 ${formatPrice(Number(draft.racket?.rental?.deposit ?? 0))}`, 1)}{row("스트링 선택", draft.stringingRequested ? `${draft.stringProduct?.name ?? ""} · ${getStringColorLabel(draft.selectedColor)} · ${formatGaugeLabel(draft.selectedGauge)}` : "교체서비스를 신청하지 않았습니다.", 2)}{draft.stringingRequested && row("작업정보", `장력 ${draft.work.tensionMain}/${draft.work.tensionCross}LB\n${draft.work.note}${draft.collectionMethod === "visit" ? `\n${draft.work.preferredDate} ${draft.work.preferredTime}` : ""}`, 5)}{row("신청자", `${draft.applicant.name} · ${draft.applicant.phone}\n${draft.applicant.email}`, 3)}{row("수령 방법", draft.collectionMethod === "visit" ? "매장 방문 수령" : `택배 수령\n${draft.shipping.postalCode} ${draft.shipping.address} ${draft.shipping.addressDetail}`, 4)}<div className="rounded-2xl border p-4"><b>환급계좌</b><p className="mb-0 text-sm">{refundBankLabel(draft.refundAccount.bank)} · {"*".repeat(Math.max(0, draft.refundAccount.holder.trim().length - 1))}{draft.refundAccount.holder.trim().slice(-1)} · {mask(draft.refundAccount.account)}</p></div></div>
    <p className="rounded-2xl bg-[#f2f4f6] p-4 text-sm">최종 결제금액은 다음 단계에서 서버의 현재 대여료·보증금·스트링 가격을 확인한 뒤 확정됩니다.</p><div className="grid grid-cols-[.72fr_1.28fr] gap-2"><button onClick={onBack} className="min-h-[52px] rounded-2xl border bg-white">이전</button><button onClick={submit} className="min-h-[52px] rounded-2xl border-0 bg-[#191f28] font-bold text-white">다음: 결제</button></div>
  </main>;
}
