import { Top } from "@toss/tds-mobile";
import { prepareRacketRentalPayment, type AppsPaymentApiError } from "../api/payments";
import { getAllowedStepForRentalDraft } from "../lib/racket-rental-validation";
import type { RacketRentalDraft } from "../types/racket-rental";
import AppsPaymentCheckoutPanel from "./AppsPaymentCheckoutPanel";


export default function RacketRentalStepSeven({ draft, paymentAttemptId, onPaymentAttemptIdChange, onInvalidStep, onPaymentError, onBack, onViewActivity }: { draft: RacketRentalDraft; paymentAttemptId: string | null; onPaymentAttemptIdChange: (v: string | null) => void; onInvalidStep: (step: 1 | 2 | 3 | 4 | 5 | 6, message: string) => void; onPaymentError: (error: AppsPaymentApiError) => void; onBack: () => void; onViewActivity: () => void }) {
  const validate = () => { const allowed = getAllowedStepForRentalDraft(draft); if (allowed !== 7) { const messages = ["", "라켓 대여 가능 여부와 기간을 다시 확인해주세요.", "스트링과 옵션 재고를 다시 확인해주세요.", "신청자 정보를 다시 확인해주세요.", "수령 방법과 배송지를 다시 확인해주세요.", "작업정보와 방문예약을 다시 확인해주세요.", "환급계좌를 다시 확인해주세요."]; onInvalidStep(allowed, messages[allowed]); return false; } return true; };
  return <main className="min-h-dvh bg-white pb-8"><section className="pt-[calc(16px+env(safe-area-inset-top))]"><Top title={<Top.TitleParagraph size={22}>라켓 대여</Top.TitleParagraph>} subtitleBottom={<Top.SubtitleParagraph size={17}>7 / 7 · Toss 로그인·결제</Top.SubtitleParagraph>} /></section><div className="px-6"><AppsPaymentCheckoutPanel paymentPurpose="racket_rental" paymentAttemptId={paymentAttemptId} onPaymentAttemptIdChange={onPaymentAttemptIdChange} validateBeforePrepare={validate} preparePayment={(attemptId, sessionToken) => prepareRacketRentalPayment({ sessionToken, attemptId, racketId: draft.racketId, days: draft.days!, applicant: draft.applicant, collectionMethod: draft.collectionMethod, shipping: draft.shipping, refundAccount: draft.refundAccount, stringing: draft.stringingRequested ? { requested: true, stringProductId: draft.stringProductId, selectedColor: draft.selectedColor, selectedGauge: draft.selectedGauge, work: draft.work } : { requested: false } })} onPaymentError={onPaymentError} onBack={onBack} onViewActivity={onViewActivity} /></div></main>;
}
