import { Top } from "@toss/tds-mobile";
import type { Product } from "../types/product";
import type { RacketAvailability, RacketDetail } from "../types/racket";
import RacketPurchaseStepOne from "./RacketPurchaseStepOne";

export default function RacketRentalStepTwo({ racket, availability, requested, productId, product, color, gauge, errorMessage = "", onRequestedChange, onStringChange, onBack, onContinue }: { racket: RacketDetail; availability: RacketAvailability; requested: boolean; productId: string; product: Product | null; color: string; gauge: string; errorMessage?: string; onRequestedChange: (value: boolean) => void; onStringChange: (id: string, product: Product | null, color: string, gauge: string) => void; onBack: () => void; onContinue: () => void }) {
  if (requested) return <div><div className="px-6 pt-4"><button type="button" className="min-h-11 border-0 bg-transparent font-bold text-[#688d00]" onClick={() => onRequestedChange(false)}>교체서비스 미신청으로 변경</button></div><RacketPurchaseStepOne racket={racket} availability={availability} quantity={1} stringProductId={productId} stringProduct={product} selectedColor={color} selectedGauge={gauge} errorMessage={errorMessage} onQuantityChange={() => {}} onStringChange={onStringChange} onBack={onBack} onContinue={onContinue} /></div>;
  return <main className="min-h-dvh bg-white px-6 pb-8 text-[#191f28]"><section className="pt-[calc(16px+env(safe-area-inset-top))]"><Top title={<Top.TitleParagraph size={22}>라켓 대여</Top.TitleParagraph>} subtitleBottom={<Top.SubtitleParagraph size={17}>2 / 7 · 선택적 스트링</Top.SubtitleParagraph>} /></section><h1>교체서비스를 선택해주세요</h1>{errorMessage && <p role="alert">{errorMessage}</p>}<div className="grid gap-3"><button type="button" className="min-h-24 rounded-2xl border border-[#688d00] bg-[#f4f9e8] p-4 text-left"><b>교체서비스 미신청</b><p className="mb-0 text-sm">스트링 상품과 작업정보 없이 대여해요.</p></button><button type="button" onClick={() => onRequestedChange(true)} className="min-h-24 rounded-2xl border border-[#d1d6db] bg-white p-4 text-left"><b>스트링 선택 후 교체서비스 신청</b><p className="mb-0 text-sm">판매 중인 스트링의 색상과 게이지를 선택해요.</p></button></div><div className="mt-6 grid grid-cols-[.72fr_1.28fr] gap-2"><button onClick={onBack} className="min-h-[52px] rounded-2xl border bg-white">이전</button><button onClick={onContinue} className="min-h-[52px] rounded-2xl border-0 bg-[#191f28] font-bold text-white">다음: 신청자</button></div></main>;
}
