import { useCallback, useEffect, useState } from "react";
import type { AppsPaymentApiError } from "../api/payments";
import { getRacketAvailability, getRacketDetail } from "../api/rackets";
import { readPendingAppsPayment, type PendingAppsPayment } from "../lib/pending-payment";
import { validateApplicant, validateShipping } from "../lib/stringing-application-validation";
import type { Product } from "../types/product";
import type { RacketRentalDraft, RentalDays, RefundAccountDraft } from "../types/racket-rental";
import type { StringingApplicantDraft, StringingCollectionMethod, StringingShippingDraft, StringingWorkDraft } from "../types/stringing";
import RacketPurchaseStepTwo from "./RacketPurchaseStepTwo";
import RacketRentalStepOne from "./RacketRentalStepOne";
import RacketRentalStepSeven from "./RacketRentalStepSeven";
import RacketRentalStepSix from "./RacketRentalStepSix";
import RacketRentalStepTwo from "./RacketRentalStepTwo";
import StringingApplicationStepThree from "./StringingApplicationStepThree";
import StringingApplicationStepTwo from "./StringingApplicationStepTwo";
import StringingPendingPaymentRecovery from "./StringingPendingPaymentRecovery";

type Step = 1 | 2 | 3 | 4 | 5 | 6 | 7;
const EMPTY_SHIPPING = { postalCode: "", address: "", addressDetail: "" };
function locationStep(): Step { const step = Number(new URLSearchParams(location.search).get("step")); return step >= 1 && step <= 7 ? step as Step : 1; }

export default function RacketRentalFlow({ racketId, onBackToDetail, onViewActivity }: { racketId: string; onBackToDetail: () => void; onViewActivity: () => void }) {
  const [step, setStep] = useState<Step>(() => locationStep()); const [load, setLoad] = useState<"loading" | "success" | "error">("loading"); const [attempt, setAttempt] = useState<string | null>(null); const [pending, setPending] = useState<PendingAppsPayment | null>(() => readPendingAppsPayment()); const [error, setError] = useState<{ step: Step; message: string } | null>(null);
  const [draft, setDraft] = useState<RacketRentalDraft>({ racketId, racket: null, availability: null, days: null, stringingRequested: false, stringProductId: "", stringProduct: null, selectedColor: "", selectedGauge: "", applicant: { name: "", email: "", phone: "" }, collectionMethod: "self_ship", shipping: EMPTY_SHIPPING, work: { tensionMain: "", tensionCross: "", note: "", preferredDate: "", preferredTime: "" }, refundAccount: { bank: "", account: "", holder: "" } });
  useEffect(() => { const c = new AbortController(); Promise.all([getRacketDetail(racketId, c.signal), getRacketAvailability(racketId, c.signal)]).then(([racket, availability]) => { if (!c.signal.aborted) { setDraft((d) => ({ ...d, racket, availability })); setLoad("success"); } }).catch(() => { if (!c.signal.aborted) setLoad("error"); }); return () => c.abort(); }, [racketId]);
  useEffect(() => { if (locationStep() === 1) return; const url = new URL(location.href); url.searchParams.set("step", "1"); history.replaceState({ view: "racket-rental", racketId, step: 1 }, "", url); setStep(1); }, [racketId]);
  const push = useCallback((nextStep: Step) => { const url = new URL(location.href); url.searchParams.set("view", "racket-rental"); url.searchParams.set("racketId", racketId); url.searchParams.set("step", String(nextStep)); history.pushState({ view: "racket-rental", racketId, step: nextStep }, "", url); setStep(nextStep); scrollTo({ top: 0 }); }, [racketId]);
  useEffect(() => { const pop = () => { const marker = readPendingAppsPayment(); if (marker) { setPending(marker); return; } setStep(locationStep()); scrollTo({ top: 0 }); }; addEventListener("popstate", pop); return () => removeEventListener("popstate", pop); }, []);
  const mutate = useCallback(<T,>(fn: (draft: RacketRentalDraft) => T) => { const marker = readPendingAppsPayment(); if (marker) { setPending(marker); return; } setAttempt(null); setDraft((current) => fn(current) as RacketRentalDraft); }, []);
  const routeError = useCallback((target: Step, message: string) => { setError({ step: target, message }); push(target); }, [push]);
  const paymentError = useCallback((e: AppsPaymentApiError) => { if (readPendingAppsPayment()) { setPending(readPendingAppsPayment()); return; } const code = e.code ?? ""; if (["RACKET_NOT_AVAILABLE", "RACKET_RENTAL_DISABLED", "RACKET_RENTAL_PRICE_INVALID", "RACKET_RENTAL_UNAVAILABLE"].includes(code)) routeError(1, "라켓 대여 가능 여부와 기간을 다시 확인해주세요."); else if (["PRODUCT_NOT_AVAILABLE", "PRODUCT_UNAVAILABLE", "VARIANT_NOT_FOUND", "VARIANT_SOLD_OUT", "VARIANT_INSUFFICIENT_STOCK", "STRING_PRICE_INVALID"].includes(code)) routeError(2, "스트링과 옵션 재고를 다시 확인해주세요."); else if (code === "VISIT_SLOT_UNAVAILABLE") routeError(5, "선택한 방문 시간을 다시 확인해주세요."); else if (code.includes("REFUND_ACCOUNT") || code === "INVALID_REQUEST") routeError(6, "환급계좌와 최종 구성을 다시 확인해주세요."); }, [routeError]);
  if (pending) return <StringingPendingPaymentRecovery pending={pending} onResolved={() => { setPending(null); setAttempt(null); }} />;
  if (load === "loading") return <main className="min-h-dvh bg-white p-6">대여 정보를 불러오고 있어요.</main>;
  if (load === "error" || !draft.racket || !draft.availability) return <main className="min-h-dvh bg-white p-6"><p>대여 정보를 불러오지 못했어요.</p><button onClick={onBackToDetail}>라켓 상세로</button></main>;
  const message = error?.step === step ? error.message : ""; const back = () => history.back();
  if (step === 7) return <RacketRentalStepSeven draft={draft} paymentAttemptId={attempt} onPaymentAttemptIdChange={setAttempt} onInvalidStep={routeError} onPaymentError={paymentError} onBack={back} onViewActivity={onViewActivity} />;
  if (step === 6) return <RacketRentalStepSix draft={draft} errorMessage={message} onChange={(refundAccount: RefundAccountDraft) => mutate((d) => ({ ...d, refundAccount }))} onEdit={push} onBack={back} onContinue={() => push(7)} />;
  if (step === 5) return !draft.stringingRequested ? <main className="min-h-dvh bg-white p-6"><h1>5 / 7 · 선택적 작업정보</h1><p className="rounded-2xl bg-[#f2f4f6] p-4">교체서비스를 신청하지 않았습니다.</p><div className="flex gap-2"><button onClick={back}>이전</button><button onClick={() => push(6)}>다음: 환급계좌</button></div></main> : <StringingApplicationStepThree mode="racket-rental" errorMessage={message} collectionMethod={draft.collectionMethod} quantity={1} work={{ racketType: `${draft.racket.brand} ${draft.racket.model}`, ...draft.work }} onWorkChange={(work: StringingWorkDraft) => mutate((d) => ({ ...d, work: { tensionMain: work.tensionMain, tensionCross: work.tensionCross, note: work.note, preferredDate: work.preferredDate, preferredTime: work.preferredTime } }))} onBack={back} onContinue={() => push(6)} />;
  if (step === 4) return <StringingApplicationStepTwo mode="racket-rental" errorMessage={message} collectionMethod={draft.collectionMethod} onCollectionMethodChange={(collectionMethod: StringingCollectionMethod) => mutate((d) => ({ ...d, collectionMethod, shipping: collectionMethod === "visit" ? EMPTY_SHIPPING : d.shipping, work: collectionMethod === "self_ship" ? { ...d.work, preferredDate: "", preferredTime: "" } : d.work }))} shipping={draft.shipping} onShippingChange={(shipping: StringingShippingDraft) => mutate((d) => ({ ...d, shipping }))} onBack={back} onContinue={() => { if (!Object.keys(validateShipping(draft.collectionMethod, draft.shipping)).length) push(5); }} />;
  if (step === 3) return <RacketPurchaseStepTwo applicant={draft.applicant} errorMessage={message} onApplicantChange={(applicant: StringingApplicantDraft) => mutate((d) => ({ ...d, applicant }))} onBack={back} onContinue={() => { if (!Object.keys(validateApplicant(draft.applicant)).length) push(4); }} />;
  if (step === 2) return <RacketRentalStepTwo racket={draft.racket} availability={draft.availability} requested={draft.stringingRequested} productId={draft.stringProductId} product={draft.stringProduct} color={draft.selectedColor} gauge={draft.selectedGauge} errorMessage={message} onRequestedChange={(requested) => mutate((d) => ({ ...d, stringingRequested: requested, ...(!requested ? { stringProductId: "", stringProduct: null, selectedColor: "", selectedGauge: "", work: { tensionMain: "", tensionCross: "", note: "", preferredDate: "", preferredTime: "" } } : {}) }))} onStringChange={(id: string, product: Product | null, color: string, gauge: string) => mutate((d) => ({ ...d, stringProductId: id, stringProduct: product, selectedColor: color, selectedGauge: gauge }))} onBack={back} onContinue={() => { if (!draft.stringingRequested || (draft.stringProduct && draft.selectedColor && draft.selectedGauge)) push(3); }} />;
  return <RacketRentalStepOne racket={draft.racket} availability={draft.availability} days={draft.days} errorMessage={message} onChange={(days: RentalDays) => mutate((d) => ({ ...d, days }))} onBack={onBackToDetail} onContinue={() => draft.days && push(2)} />;
}
