import { ObjectId, type ClientSession, type Db } from "mongodb";
import { getMongoDatabase } from "@/lib/mongodb";
import type { AdminPrincipal } from "@/features/admin-auth/admin-auth.types";
import type { AdminAuditHistoryItem } from "@/features/admin-audit/admin-audit.types";
import { staffAuditActions, staffAuditChangedFields, type StaffAuditAction, type StaffAuditActor, type StaffAuditChangedField, type StaffAuditSnapshot } from "./staff.audit";
export const STAFF_AUDIT_COLLECTION_NAME = "staff_audit_events";
export type StaffAuditEventDocument = { _id: ObjectId; staffProfileId: ObjectId; action: StaffAuditAction; actor: StaffAuditActor; occurredAt: Date; fromVersionAt: Date | null; toVersionAt: Date; before: StaffAuditSnapshot | null; after: StaffAuditSnapshot; changedFields: StaffAuditChangedField[] };
export async function insertStaffAuditEvent(input: { database: Db; session: ClientSession; eventId: ObjectId; staffProfileId: ObjectId; action: StaffAuditAction; actor: AdminPrincipal; occurredAt: Date; fromVersionAt: Date | null; toVersionAt: Date; before: StaffAuditSnapshot | null; after: StaffAuditSnapshot; changedFields: readonly StaffAuditChangedField[] }) { const document: StaffAuditEventDocument = { _id: input.eventId, staffProfileId: input.staffProfileId, action: input.action, actor: { adminId: new ObjectId(input.actor.id), displayName: input.actor.displayName, role: input.actor.role }, occurredAt: input.occurredAt, fromVersionAt: input.fromVersionAt, toVersionAt: input.toVersionAt, before: input.before, after: input.after, changedFields: [...input.changedFields] }; await input.database.collection<StaffAuditEventDocument>(STAFF_AUDIT_COLLECTION_NAME).insertOne(document, { session: input.session }); }
const actionLabels = { created: "직원 소개 생성", updated: "직원 소개 수정" };
const fieldLabels: Record<StaffAuditChangedField, string> = { role: "직책·역할", responsibility: "담당 업무", name: "직원 이름", nameDisclosure: "이름 공개 확인", publicationStatus: "공개 상태", displayOrder: "표시 순서" };
export async function listAdminStaffAuditHistory(staffProfileId: string): Promise<AdminAuditHistoryItem[]> { if (!ObjectId.isValid(staffProfileId)) return []; const documents = await (await getMongoDatabase()).collection<StaffAuditEventDocument>(STAFF_AUDIT_COLLECTION_NAME).find({ staffProfileId: new ObjectId(staffProfileId) }, { projection: { action: 1, "actor.displayName": 1, occurredAt: 1, changedFields: 1 } }).sort({ occurredAt: -1, _id: -1 }).limit(50).toArray(); return documents.flatMap((event) => event._id instanceof ObjectId && event.occurredAt instanceof Date && staffAuditActions.includes(event.action) && typeof event.actor?.displayName === "string" && Array.isArray(event.changedFields) && event.changedFields.every((field) => staffAuditChangedFields.includes(field)) ? [{ id: event._id.toHexString(), actionLabel: actionLabels[event.action], actorDisplayName: event.actor.displayName, occurredAt: event.occurredAt.toISOString(), changedFieldLabels: event.changedFields.map((field) => fieldLabels[field]) }] : []); }
